version: SEIMS-Win64.{build}.{branch}
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
image: Visual Studio 2013
configuration: Release
platform: x64
services: mongodb
build:
  parallel: true
  verbosity: minimal
environment:
  global:
    GDAL_HOME: "C:\\gdal"
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_ENV: "cmd /E:ON /V:ON /C .\\doc\\ci\\appveyor\\run_with_env.cmd"
install:
  # download compiled gdal and install it
  - ps: mkdir C:\gdal | out-null
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3.zip -FileName gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3-libs.zip -FileName gdallibs.zip
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET PATH=C:\\gdal\\bin\\ms\\apps;C:\\gdal\\bin\\curl;C:\\gdal\\bin\\proj\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"
  - "SET GDAL_DIR=C:\\gdal"
  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""
  # compile mongo-c-driver
  - appveyor DownloadFile https://github.com/mongodb/mongo-c-driver/releases/download/1.5.5/mongo-c-driver-1.5.5.tar.gz -FileName mongo-c-driver-1.5.5.tar.gz
  - 7z x mongo-c-driver-1.5.5.tar.gz
  - 7z x mongo-c-driver-1.5.5.tar -oC:\
  - cd C:\mongo-c-driver-1.5.5
  - ps: "ls"
  - cd src\libbson
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - cd ..\..
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -DBSON_ROOT_DIR=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - "SET MONGOC_ROOT=C:\\mongo-c-driver"
  - "SET MONGOC_LIB_DIR=C:\\mongo-c-driver\\bin"
  - "SET PATH=C:\\mongo-c-driver\\bin;%PATH%"
  # install MS-MPI
  - cd C:\projects\seims
  - "powershell doc\\ci\\appveyor\\install-msmpi.ps1"
  - "doc\\ci\\appveyor\\SetEnvMPI.cmd"
build_script:
  # make directory for releases
  - cd C:\projects\seims
  - mkdir seims_win64bit\seims
  - mkdir seims_win64bit\bin
  - ps: "ls"
  # Build 64-bit release version on Windows, and build unittest.
  - mkdir build64Rel
  - cd build64Rel
  # Do not compile UnitTest now. -DUNITTEST=1
  - cmake -G "Visual Studio 12 2013 Win64" .. -DINSTALL_PREFIX=C:\projects\seims\seims_win64bit\bin
  - msbuild.exe ALL_BUILD.vcxproj /p:Configuration=Release /maxcpucount:4 /clp:Summary
  - msbuild.exe INSTALL.vcxproj /p:Configuration=Release /maxcpucount:4
  # copy files to releases
  - copy C:\projects\seims\*.md C:\projects\seims\seims_win64bit
  - xcopy C:\projects\seims\data C:\projects\seims\seims_win64bit\data /e /c /i /y
  - copy C:\projects\seims\seims\*.* C:\projects\seims\seims_win64bit\seims
  - move C:\projects\seims\seims_win64bit\seims\Firewall_for_Windows.bat C:\projects\seims\seims_win64bit\bin
  - xcopy C:\projects\seims\seims\preprocess C:\projects\seims\seims_win64bit\seims\preprocess /e /c /i /y
  - xcopy C:\projects\seims\seims\postprocess C:\projects\seims\seims_win64bit\seims\postprocess /e /c /i /y
  - xcopy C:\projects\seims\seims\parameters_sensitivity C:\projects\seims\seims_win64bit\seims\parameters_sensitivity /e /c /i /y
  - xcopy C:\projects\seims\seims\scenario_analysis C:\projects\seims\seims_win64bit\seims\scenario_analysis /e /c /i /y
  - xcopy C:\projects\seims\seims\calibration C:\projects\seims\seims_win64bit\seims\calibration /e /c /i /y
#test_script:
  # Run unit test.
  #- C:\projects\seims\seims_win64bit\bin\seims_ut_exec.exe
artifacts:
- path: seims_win64bit
  type: zip
deploy:
- provider: GitHub
  auth_token:
    secure: /br3cLS15FA2D1MnSbZPrsRxLMfN9wNQaRZ30ye1adfFK7HOHmRmPtWZGdgZzuke
  artifact: seims_win64bit.zip
  force_update: true
  on:
    appveyor_repo_tag: true
